<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>LiveSplit</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <TargetFramework>net4.8.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Version>1.0.0</Version>

    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>

  <Import Project="..\..\LiveSplitDir.props" />

  <ItemGroup>
    <Reference Include="LiveSplit.Core">
      <HintPath>$(LiveSplitDir)\LiveSplit.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UpdateManager">
      <HintPath>$(LiveSplitDir)\UpdateManager.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PolySharp" Version="1.16.0" PrivateAssets="all" />
  </ItemGroup>

</Project>
